#
# see also https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/defaults.1.html
#

mac_defaults_settings:
  # Finder
  - {
    domain: com.apple.finder,
    key: NewWindowTarget,
    type: string,
    value: PfDe,
  }
  - {
    domain: com.apple.finder,
    key: ShowExternalHardDrivesOnDesktop,
    type: bool,
    value: true,
  }
  - {
    domain: com.apple.finder,
    key: ShowMountedServersOnDesktop,
    type: bool,
    value: true,
  }
  - {
    domain: com.apple.finder,
    key: ShowRemovableMediaOnDesktop,
    type: bool,
    value: true,
  }
  - {
    domain: com.apple.finder,
    key: ShowStatusBar,
    type: bool,
    value: true,
  }
  - {
    domain: com.apple.finder,
    key: ShowPathbar,
    type: bool,
    value: true,
  }
  - {
    domain: com.apple.finder,
    key: AppleShowAllFiles,
    type: bool,
    value: true,
  }

  # Dock
  - {
    domain: com.apple.dock,
    key: autohide,
    type: bool,
    value: true,
  }
  - {
    domain: com.apple.dock,
    key: magnification,
    type: bool,
    value: false,
  }
  - {
    domain: NSGlobalDomain,
    key: AppleShowAllExtensions,
    type: bool,
    value: true
  }
