homebrew_taps:
  - caskroom/cask

homebrew_packages:
  - aircrack-ng
  - ansible
  - autoconf
  - autopsy
  - avr-binutils
  - avr-gcc
  - avr-libc
  - binutils
  - binwalk
  - boost
  - cairo
  - cmake
  - cmatrix
  - coreutils
  - cpulimit
  - curl
  - czmq
  - dex2jar
  - dirmngr
  - doxygen
  - eigen
  - fcrackzip
  - ffmpeg
  - figlet
  - fontconfig
  - fontforge
  - freetype
  - gd
  - gdb
  - gdbm
  - gettext
  - ghostscript
  - git
  - glfw
  - glib
  - gmp
  - gnupg
  - gnupg2
  - gnuplot
  - gnutls
  - go
  - gobject-introspection
  - gpg-agent
  - graphviz
  - harfbuzz
  - hexedit
  - icu4c
  - ilmbase
  - imagemagick
  - isl
  - jansson
  - john
  - jpeg
  - lame
  - libassuan
  - libelf
  - libevent
  - libewf
  - libffi
  - libgcrypt
  - libgpg-error
  - libksba
  - libmagic
  - libmpc
  - libpng
  - libsodium
  - libtasn1
  - libtiff
  - libtool
  - libusb
  - libusb-compat
  - libyaml
  - little-cms2
  - llvm
  - lua
  - lzo
  - mongodb
  - mpfr
  - mysql
  - nettle
  - nmap
  - node
  - numpy
  - opencv
  - openexr
  - openjpeg
  - openssl
  - p7zip
  - pandoc
  - pandoc-crossref
  - pango
  - pcre
  - pdf2svg
  - pdfcrack
  - picocom
  - pinentry
  - pixman
  - pkcrack
  - pkg-config
  - pngcheck
  - poppler
  - pth
  - pwgen
  - python@2
  - qemu
  - qpdf
  - radare2
  - rbenv
  - readline
  - reattach-to-user-namespace
  - redis
  - ruby-build
  - simavr
  - sleuthkit
  - socat
  - source-highlight
  - sqlite
  - sqlmap
  - squashfs
  - ssdeep
  - tmux
  - tree
  - { name : vim, install_options : with-lua }
  - wakeonlan
  - watch
  - webp
  - wget
  - x264
  - xvid
  - xz
  - yara
  - yarn
  - zeromq
  - zlib
  - zsh
  - zsh-completions

homebrew_cask_packages:
  - docker
  - firefox
  - google-chrome
  - slack
  - skype
  - sourcetree
  - virtualbox
  - visual-studio-code
